### ISSUE TITLE
Everything under a single sub-domain?

### ISSUE THREAD

**Issue by felipecrs** [gmoirod/helm-workadventure#4]
Do you think it would be possible to deploy everything under a single subdomain, like the following:

```
https://workadventure.minikube/[play | maps | pusher | uploader | api]
```

Instead of:

```
https://[play | maps | pusher | uploader | api].workadventure.minikube
```

**Comment by felipecrs** [comment]
This is not an real issue so I don't think it makes sense to keep it open, but feel free to answer it if you want. Thank you anyway!

**Comment by gmoirod** [comment]
@felipecrs at first this is not the "natural" kubernetes way. Each service get its own ingress. So 1 service = 1 subdomain. And workadventu.re is composed of several services. 
But it may be possible to add a single ingress with 1 rule per service. Each rule pointing to a different service).

**Comment by felipecrs** [comment]
> But it may be possible to add a single ingress with 1 rule per service. Each rule pointing to a different service).

That part is doable indeed, I just wonder if the underlying workadventure services allow to set baseUrls for each services including a /prefix like that.

**Comment by gmoirod** [comment]
I did not have the idea to try.
And as I do not own workadventu.re, I cannot tell for them.
Sorry 😊

**Comment by felipecrs** [comment]
Alright, thank you.
